# Pandas Demo

In [1]:
import pandas as pd

In [2]:
d1 ={
    "name": ["Alice", "Bob", "Charlie"]
}
df1 = pd.Series(d1["name"])
df1.head()

0      Alice
1        Bob
2    Charlie
dtype: object

In [3]:
d2 = {
    "name": ["Alice", "Bob", "Charlie"],
    "city": ["New York", "Los Angeles", "Chicago"],
    "salary": [70000, 80000, 90000]
}
df2 = pd.DataFrame(d2)
df2.head()

      name         city  salary
0    Alice     New York   70000
1      Bob  Los Angeles   80000
2  Charlie      Chicago   90000

In [4]:
from pathlib import Path
current_dir = Path.cwd()
data_file = current_dir / "data/sample.csv"
df = pd.read_csv(data_file)
df.head()

      name       city  salary                  email
0  vishwas  bangalore   23000  vishwas@cloudthat.com
1     john      delhi    2000     john.doe@gmail.com
2     rita       pune    6000                ritacom
3     macy     mumbai    8000       macy-j@gmail.com

In [6]:
# Apply email validation from utilities on email column
from utilities.email_utils import is_valid_email
df["is_valid_email"] = df["email"].apply(is_valid_email)
df.head()

      name       city  salary                  email  is_valid_email
0  vishwas  bangalore   23000  vishwas@cloudthat.com            True
1     john      delhi    2000     john.doe@gmail.com            True
2     rita       pune    6000                ritacom           False
3     macy     mumbai    8000       macy-j@gmail.com           False

## Preprocessing of data using pandas
- Remove rows with missing values
- Fill missing values with default values
- Convert columns to appropriate data types
- Remove duplicate rows
- Apply custom data validation functions
- Normalize column names
- Encode categorical variables
- Scale numerical features

In [7]:
# drop the rows where is_valid_email is False
df = df[df["is_valid_email"]]
df.head()

      name       city  salary                  email  is_valid_email
0  vishwas  bangalore   23000  vishwas@cloudthat.com            True
1     john      delhi    2000     john.doe@gmail.com            True

In [8]:
# Define a synthetic dictionary for testing purposes of data preprocessing
d3 ={
    "name": ["Alice", "Bob", "Charlie", None],
    "email": ["alice@example.com", "bob@example", "charlie@example.com", "dave@example.com"],
    "city": ["New York", "Los Angeles", "Chicago", "San Francisco"],
    "salary": [70000, 80000, None, "90000"]
}

df3 = pd.DataFrame(d3)
df3.head()

      name                email           city salary
0    Alice    alice@example.com       New York  70000
1      Bob          bob@example    Los Angeles  80000
2  Charlie  charlie@example.com        Chicago   None
3     None     dave@example.com  San Francisco  90000

In [9]:
df4 = df3.copy()
df4.dropna(inplace=True)
df4.head()

    name              email         city salary
0  Alice  alice@example.com     New York  70000
1    Bob        bob@example  Los Angeles  80000

In [10]:
df5 = df3.copy()
df5.fillna({
    "name": "Unknown",
    "email": "unknown@example.com",
    "city": "Unknown",
    "salary": 0
}, inplace=True)
df5.head()

      name                email           city salary
0    Alice    alice@example.com       New York  70000
1      Bob          bob@example    Los Angeles  80000
2  Charlie  charlie@example.com        Chicago      0
3  Unknown     dave@example.com  San Francisco  90000